// ============================================================
// Module 3: Report Service — Blob Storage + SQL persistence
// Owner: Hassan Asif (02-131232-113)
//
// NuGet packages needed:
//   dotnet add package Azure.Storage.Blobs
//   dotnet add package Microsoft.EntityFrameworkCore.SqlServer
//   dotnet add package Microsoft.EntityFrameworkCore.Tools
// ============================================================
using Azure.Storage.Blobs;
using System.Security.Cryptography;
using System.Text;

public class ReportService
{
    private readonly BlobServiceClient _blobClient;
    private readonly string _containerName;

    public ReportService()
    {
        var connStr = Environment.GetEnvironmentVariable("AZURE_BLOB_CONNECTION")
            ?? throw new Exception("AZURE_BLOB_CONNECTION not set");
        _containerName = Environment.GetEnvironmentVariable("AZURE_BLOB_CONTAINER") ?? "reports";
        _blobClient    = new BlobServiceClient(connStr);
    }

    /// <summary>
    /// 1. Formats the summary into a text document
    /// 2. Computes SHA-256 hash
    /// 3. Uploads to Azure Blob Storage
    /// 4. (TODO Hassan) Persists task record to Azure SQL via EF Core
    /// Returns: BlobUrl + OutputHash
    /// </summary>
    public async Task<ReportOutput> GenerateAndStoreAsync(ReportRequest request)
    {
        // ── Step 1: Format the report ──────────────────────────────────
        var reportContent = FormatReport(request.Topic, request.Summary);

        // ── Step 2: Compute SHA-256 hash ──────────────────────────────
        var hashBytes  = SHA256.HashData(Encoding.UTF8.GetBytes(reportContent));
        var outputHash = Convert.ToHexString(hashBytes).ToLower();

        // ── Step 3: Upload to Azure Blob Storage ───────────────────────
        var container   = _blobClient.GetBlobContainerClient(_containerName);
        await container.CreateIfNotExistsAsync();

        var blobName    = $"{request.TaskId}.txt";
        var blobClient  = container.GetBlobClient(blobName);

        using var stream = new MemoryStream(Encoding.UTF8.GetBytes(reportContent));
        await blobClient.UploadAsync(stream, overwrite: true);

        var blobUrl = blobClient.Uri.ToString();

        // ── Step 4 (TODO Hassan): Save to Azure SQL via EF Core ────────
        // Example:
        // await _db.Reports.AddAsync(new ReportEntity
        // {
        //     Id         = Guid.NewGuid(),
        //     TaskId     = Guid.Parse(request.TaskId),
        //     BlobUrl    = blobUrl,
        //     OutputHash = outputHash,
        //     CreatedAt  = DateTime.UtcNow
        // });
        // await _db.SaveChangesAsync();

        return new ReportOutput(blobUrl, outputHash);
    }

    private static string FormatReport(string topic, string summary) =>
        $"""
        ====================================
        INTELLIFLOW AUTOMATED RESEARCH REPORT
        ====================================
        Topic:     {topic}
        Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

        ── SUMMARY ──────────────────────────
        {summary}

        ── END OF REPORT ────────────────────
        Generated by IntelliFlow | Cloud Computing Lab Project | BU Karachi
        """;
}

public record ReportOutput(string BlobUrl, string OutputHash);
