// ============================================================
// Module 3: Report Service — Supabase Storage + PostgreSQL
// Owner: Hassan Asif (02-131232-113)
// ============================================================
using System.Security.Cryptography;
using System.Text;
using Supabase;

public class ReportService
{
    private readonly IntelliFlowDbContext _dbContext;

    public ReportService(IntelliFlowDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task<ReportResult> GenerateReportAsync(string taskId, string topic, string summary)
    {
        // Step 1 - Report content banao
        var reportContent = FormatReport(topic, summary);

        // Step 2 - SHA-256 hash
        var outputHash = Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(reportContent)));

        // Step 3 - Supabase Upload
        var supabaseUrl = Environment.GetEnvironmentVariable("SUPABASE_URL")
            ?? throw new Exception("SUPABASE_URL not set");
        var supabaseKey = Environment.GetEnvironmentVariable("SUPABASE_SERVICE_ROLE_KEY")
            ?? Environment.GetEnvironmentVariable("SUPABASE_ANON_KEY")
            ?? throw new Exception("SUPABASE_SERVICE_ROLE_KEY or SUPABASE_ANON_KEY not set");

        var client = new Supabase.Client(supabaseUrl, supabaseKey);
        await client.InitializeAsync();

        var bytes = Encoding.UTF8.GetBytes(reportContent);
        await client.Storage
            .From("reports")
            .Upload(bytes, $"{taskId}.txt");

        var blobUrl = $"{supabaseUrl}/storage/v1/object/public/reports/{taskId}.txt";

        // Step 4 - Save to DB
        var report = new ReportRecord
        {
            TaskId = taskId,
            Topic = topic,
            BlobUrl = blobUrl,
            OutputHash = outputHash,
            CreatedAt = DateTime.UtcNow
        };
        _dbContext.Reports.Add(report);
        await _dbContext.SaveChangesAsync();

        return new ReportResult { BlobUrl = blobUrl, OutputHash = outputHash };
    }

    private static string FormatReport(string topic, string summary) =>
        $"""
        ====================================
        INTELLIFLOW AUTOMATED RESEARCH REPORT
        ====================================
        Topic:     {topic}
        Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

        ── SUMMARY ──────────────────────────
        {summary}

        ── END OF REPORT ────────────────────
        Generated by IntelliFlow | Cloud Computing Lab Project | BU Karachi
        """;
}